doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        dql:
            datetime_functions: #funkcje oro/doctrine-extensions  
                date: Oro\ORM\Query\AST\Functions\SimpleFunction
                time: Oro\ORM\Query\AST\Functions\SimpleFunction
                timestamp: Oro\ORM\Query\AST\Functions\SimpleFunction
                convert_tz: Oro\ORM\Query\AST\Functions\DateTime\ConvertTz
            numeric_functions:
                timestampdiff: Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff
                dayofyear: Oro\ORM\Query\AST\Functions\SimpleFunction
                dayofmonth: Oro\ORM\Query\AST\Functions\SimpleFunction
                dayofweek: Oro\ORM\Query\AST\Functions\SimpleFunction
                week: Oro\ORM\Query\AST\Functions\SimpleFunction
                day: Oro\ORM\Query\AST\Functions\SimpleFunction
                hour: Oro\ORM\Query\AST\Functions\SimpleFunction
                minute: Oro\ORM\Query\AST\Functions\SimpleFunction
                month: Oro\ORM\Query\AST\Functions\SimpleFunction
                quarter: Oro\ORM\Query\AST\Functions\SimpleFunction
                second: Oro\ORM\Query\AST\Functions\SimpleFunction
                year: Oro\ORM\Query\AST\Functions\SimpleFunction
                sign: Oro\ORM\Query\AST\Functions\Numeric\Sign
                pow: Oro\ORM\Query\AST\Functions\Numeric\Pow
                round: Oro\ORM\Query\AST\Functions\Numeric\Round
                ceil: Oro\ORM\Query\AST\Functions\SimpleFunction
            string_functions:
                md5: Oro\ORM\Query\AST\Functions\SimpleFunction
                group_concat: Oro\ORM\Query\AST\Functions\String\GroupConcat
                concat_ws: Oro\ORM\Query\AST\Functions\String\ConcatWs
                cast: Oro\ORM\Query\AST\Functions\Cast
                replace: Oro\ORM\Query\AST\Functions\String\Replace
                date_format: Oro\ORM\Query\AST\Functions\String\DateFormat
                collate: App\Infrastructure\Shared\Doctrine\Query\Collate
        auto_mapping: true
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        default_entity_manager: default
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
                alias: GedmoLoggable
                is_bundle: false
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/User/Model'
                prefix: 'App\Domain\User\Model'
                alias: 'User'
            Message:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Message/Model'
                prefix: 'App\Domain\Message\Model'
                
