doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Infrastructure\migrations': '%kernel.project_dir%/src/Infrastructure/migrations'
    enable_profiler: '%kernel.debug%'
