framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus: [ ]
            query.bus: [ ]
            message.bus: [ ]
        transports:
            sync: sync://
            doctrine_async:
                dsn: doctrine://default
                options:
                    table_name: queue_jobs
                    auto_setup: false
            rabbit_mq:
                dsn: '%env(RABBIT_MQ_DSN)%'
                serializer: messenger.transport.symfony_serializer
            rabbit_mq_async:
                dsn: '%env(RABBIT_MQ_ASYNC_DSN)%'
                serializer: messenger.transport.symfony_serializer
        routing:
            App\Application\Shared\Command\AsyncCommandInterface: rabbit_mq_async
            App\Application\Shared\Query\QueryInterface: sync
            App\Application\Shared\Command\CommandInterface: sync
            App\Application\Shared\Message\MessageInterface: rabbit_mq_async
        reset_on_message: true
