framework:
    workflows:
        message:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Domain\Message\Model\MessageContext
            initial_marking: !php/const App\Domain\Message\Model\MessageContext::CREATED
            places:
                - !php/const App\Domain\Message\Model\MessageContext::CREATED
                - !php/const App\Domain\Message\Model\MessageContext::QUEUE
                - !php/const App\Domain\Message\Model\MessageContext::SENT
                - !php/const App\Domain\Message\Model\MessageContext::ERROR
            transitions:
                to_queue:
                    from: !php/const App\Domain\Message\Model\MessageContext::CREATED
                    to: !php/const App\Domain\Message\Model\MessageContext::QUEUE
                mark_error:
                    from:
                        - !php/const App\Domain\Message\Model\MessageContext::CREATED
                        - !php/const App\Domain\Message\Model\MessageContext::QUEUE
                    to: !php/const App\Domain\Message\Model\MessageContext::ERROR
                send:
                    from:
                        - !php/const App\Domain\Message\Model\MessageContext::QUEUE
                        - !php/const App\Domain\Message\Model\MessageContext::ERROR
                    to: !php/const App\Domain\Message\Model\MessageContext::SENT
                    
