services:
  api:
    image: $IMAGE_NAME
    ports:
      - ${DOCKER_HOST_WWW_PORT:-80}:80
    deploy:
      replicas: $REPLICAS_NUM
      restart_policy:
        condition: any
      update_config:
        parallelism: $PARALLELISM_NUM
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: $PARALLELISM_NUM
        order: stop-first
        failure_action: pause
      resources:
        limits:
          cpus: $LIMIT_CPUS
          memory: $LIMIT_MEMORY
    volumes:
      - ./.env:/app/.env.local
      - ./files:/app/var/files
      - ./files_public:/app/public/uploads
      - ./log:/app/var/log
    cap_add:
      - SYS_PTRACE
    extra_hosts:
      - "host.docker.internal:host-gateway"
#  mailhog:
#    image: mailhog/mailhog:latest
#    ports:
#      - ${DOCKER_HOST_MAILHOG_PORT:-8025}:8025

networks:
  default:
    name: ji-network-${RUN_ENV}
