when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
        
authentication_token:
    path: /login
    methods: ['POST']
    
gesdinet_jwt_refresh_token:
    path: /token/refresh
    
api_platform:
    resource: .
    type: api_platform
    prefix: /
