### Login as recruiter
POST http://localhost/login
Content-Type: application/json
Accept: application/json

{ "email" : "recruiter@test.com", "password": "test1234" }

> {%
client.global.set("auth_token", response.body.token);
client.global.set("refresh_token", response.body.refresh_token);
%}


### login as employee
POST http://localhost/login
Content-Type: application/json
Accept: application/json

{ "email" : "employee@test.com", "password": "test1234" }

> {%
client.global.set("auth_token", response.body.token);
client.global.set("refresh_token", response.body.refresh_token);
%}


### login as admin
POST http://localhost/login
Content-Type: application/json
Accept: application/json

{ "email" : "admin@test.com", "password": "test1234" }

> {%
    client.global.set("auth_token", response.body.token);
    client.global.set("refresh_token", response.body.refresh_token);
%}


### refresh token
POST http://localhost/token/refresh
Content-Type: application/x-www-form-urlencoded

refresh_token={{refresh_token}}

> {%
client.global.set("auth_token", response.body.token);
client.global.set("refresh_token", response.body.refresh_token);
%}
