### User collection
GET http://localhost/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create user
POST http://localhost/users
Content-Type: application/json
Accept: application/json

{
    "email": "test@example.com",
    "password": "stringst",
    "firstName": "string",
    "lastName": "string"
}

